version: '3'
services:
  redis:
    stop_grace_period: 10s
    image: redis
    ports:
      - "6666:6379"
      - "127.0.0.1:6379:6379"
  socket_proxy:
    stop_grace_period: 10s
    image: rocketcyber/socket_proxy:latest
    ports:
      - '8080:8080'
    depends_on:
      - redis
    environment:
      - SOCKET_PROXY_SECRET
      - REDIS_URL=redis://redis:6379/0

  mailcatcher:
    stop_grace_period: 10s
    image: schickling/mailcatcher
    ports:
      - '1080:1080'
      - '1025:1025'
