COUNTRIES = {
  "US" => { "full_name" => "United States" },
  "BR" => { "full_name" => "Brazil" },
  "RU" => { "full_name" => "Russia" },
  "GB" => { "full_name" => "United Kingdom" },
  "DE" => { "full_name" => "Germany" },
  "PL" => { "full_name" => "Poland" },
  "AU" => { "full_name" => "Australia" },
  "IN" => { "full_name" => "India" },
  "UA" => { "full_name" => "Ukraine" },
  "CA" => { "full_name" => "Canada" },
  "FR" => { "full_name" => "France" },
  "ID" => { "full_name" => "Indonesia" },
  "NL" => { "full_name" => "Netherlands" },
  "CN" => { "full_name" => "China" },
  "RO" => { "full_name" => "Romania" },
  "IT" => { "full_name" => "Italy" },
  "ES" => { "full_name" => "Spain" },
  "AR" => { "full_name" => "Argentina" },
  "JP" => { "full_name" => "Japan" },
  "CH" => { "full_name" => "Switzerland" },
  "HK" => { "full_name" => "Hong Kong" },
  "KR" => { "full_name" => "South Korea" },
  "SE" => { "full_name" => "Sweden" },
  "BG" => { "full_name" => "Bulgaria" },
  "BD" => { "full_name" => "Bangladesh" },
  "CZ" => { "full_name" => "Czech Republic" },
  "IR" => { "full_name" => "Iran" },
  "TR" => { "full_name" => "Turkey" },
  "AT" => { "full_name" => "Austria" },
  "NZ" => { "full_name" => "New Zealand" },
  "ZA" => { "full_name" => "South Africa" },
  "TH" => { "full_name" => "Thailand" },
  "SG" => { "full_name" => "Singapore" },
  "PH" => { "full_name" => "Philippines" },
  "MX" => { "full_name" => "Mexico" },
  "DK" => { "full_name" => "Denmark" },
  "NO" => { "full_name" => "Norway" },
  "FI" => { "full_name" => "Finland" },
  "BE" => { "full_name" => "Belgium" },
  "IL" => { "full_name" => "Israel" },
  "VN" => { "full_name" => "Vietnam" },
  "CL" => { "full_name" => "Chile" },
  "LV" => { "full_name" => "Latvia" },
  "SI" => { "full_name" => "Slovenia" },
  "TW" => { "full_name" => "Taiwan" },
  "HU" => { "full_name" => "Hungary" },
  "MY" => { "full_name" => "Malaysia" },
  "IE" => { "full_name" => "Ireland" },
  "GR" => { "full_name" => "Greece" },
  "SK" => { "full_name" => "Slovakia" },
  "RS" => { "full_name" => "Serbia" },
  "CO" => { "full_name" => "Colombia" },
  "MD" => { "full_name" => "Moldova" },
  "NG" => { "full_name" => "Nigeria" },
  "LB" => { "full_name" => "Lebanon" },
  "SA" => { "full_name" => "Saudi Arabia" },
  "PK" => { "full_name" => "Pakistan" },
  "LT" => { "full_name" => "Lithuania" },
  "KZ" => { "full_name" => "Kazakhstan" },
  "HR" => { "full_name" => "Croatia" },
  "BY" => { "full_name" => "Belarus" },
  "EE" => { "full_name" => "Estonia" },
  "PA" => { "full_name" => "Panama" },
  "IQ" => { "full_name" => "Iraq" },
  "PT" => { "full_name" => "Portugal" },
  "EC" => { "full_name" => "Ecuador" },
  "KE" => { "full_name" => "Kenya" },
  "LU" => { "full_name" => "Luxembourg" },
  "CY" => { "full_name" => "Cyprus" },
  "KH" => { "full_name" => "Cambodia" },
  "GE" => { "full_name" => "Georgia" },
  "NP" => { "full_name" => "Nepal" },
  "VE" => { "full_name" => "Venezuela" },
  "AE" => { "full_name" => "United Arab Emirates" },
  "CR" => { "full_name" => "Costa Rica" },
  "AM" => { "full_name" => "Armenia" },
  "HN" => { "full_name" => "Honduras" },
  "PR" => { "full_name" => "Puerto Rico" },
  "TZ" => { "full_name" => "Tanzania" },
  "IS" => { "full_name" => "Iceland" },
  "MM" => { "full_name" => "Myanmar [Burma]" },
  "EG" => { "full_name" => "Egypt" },
  "GH" => { "full_name" => "Ghana" },
  "KW" => { "full_name" => "Kuwait" },
  "AL" => { "full_name" => "Albania" },
  "AF" => { "full_name" => "Afghanistan" },
  "PE" => { "full_name" => "Peru" },
  "PY" => { "full_name" => "Paraguay" },
  "AO" => { "full_name" => "Angola" },
  "MK" => { "full_name" => "Macedonia" },
  "UZ" => { "full_name" => "Uzbekistan" },
  "PS" => { "full_name" => "Palestinian Territories" },
  "AZ" => { "full_name" => "Azerbaijan" },
  "KG" => { "full_name" => "Kyrgyzstan" },
  "MN" => { "full_name" => "Mongolia" },
  "GT" => { "full_name" => "Guatemala" },
  "UG" => { "full_name" => "Uganda" },
  "DO" => { "full_name" => "Dominican Republic" },
  "BO" => { "full_name" => "Bolivia" },
  "BA" => { "full_name" => "Bosnia and Herzegovina" },
  "MT" => { "full_name" => "Malta" },
  "SV" => { "full_name" => "El Salvador" },
  "JO" => { "full_name" => "Jordan" },
  "UY" => { "full_name" => "Uruguay" },
  "MU" => { "full_name" => "Mauritius" },
  "CD" => { "full_name" => "Congo - Kinshasa" },
  "MZ" => { "full_name" => "Mozambique" },
  "ZW" => { "full_name" => "Zimbabwe" },
  "NI" => { "full_name" => "Nicaragua" },
  "BZ" => { "full_name" => "Belize" },
  "LA" => { "full_name" => "Laos" },
  "BW" => { "full_name" => "Botswana" },
  "BH" => { "full_name" => "Bahrain" },
  "TN" => { "full_name" => "Tunisia" },
  "LI" => { "full_name" => "Liechtenstein" },
  "PG" => { "full_name" => "Papua New Guinea" },
  "LK" => { "full_name" => "Sri Lanka" },
  "ME" => { "full_name" => "Montenegro" },
  "ZM" => { "full_name" => "Zambia" },
  "SC" => { "full_name" => "Seychelles" },
  "BM" => { "full_name" => "Bermuda" },
  "GI" => { "full_name" => "Gibraltar" },
  "RW" => { "full_name" => "Rwanda" },
  "CM" => { "full_name" => "Cameroon" },
  "BT" => { "full_name" => "Bhutan" },
  "BF" => { "full_name" => "Burkina Faso" },
  "CI" => { "full_name" => "Côte d’Ivoire" },
  "DZ" => { "full_name" => "Algeria" },
  "SO" => { "full_name" => "Somalia" },
  "VG" => { "full_name" => "British Virgin Islands" },
  "SL" => { "full_name" => "Sierra Leone" },
  "MW" => { "full_name" => "Malawi" },
  "OM" => { "full_name" => "Oman" },
  "NA" => { "full_name" => "Namibia" },
  "NC" => { "full_name" => "New Caledonia" },
  "QA" => { "full_name" => "Qatar" },
  "KY" => { "full_name" => "Cayman Islands" },
  "TT" => { "full_name" => "Trinidad and Tobago" },
  "MA" => { "full_name" => "Morocco" },
  "GA" => { "full_name" => "Gabon" },
  "BN" => { "full_name" => "Brunei" },
  "TJ" => { "full_name" => "Tajikistan" },
  "CG" => { "full_name" => "Congo - Brazzaville" },
  "JM" => { "full_name" => "Jamaica" },
  "MV" => { "full_name" => "Maldives" },
  "GN" => { "full_name" => "Guinea" },
  "HT" => { "full_name" => "Haiti" },
  "BJ" => { "full_name" => "Benin" },
  "IM" => { "full_name" => "Isle of Man" },
  "FJ" => { "full_name" => "Fiji" },
  "VU" => { "full_name" => "Vanuatu" },
  "LR" => { "full_name" => "Liberia" },
  "MO" => { "full_name" => "Macau SAR China" },
  "ML" => { "full_name" => "Mali" },
  "LY" => { "full_name" => "Libya" },
  "BB" => { "full_name" => "Barbados" },
  "BI" => { "full_name" => "Burundi" },
  "SN" => { "full_name" => "Senegal" },
  "LS" => { "full_name" => "Lesotho" },
  "SZ" => { "full_name" => "Swaziland" },
  "SD" => { "full_name" => "Sudan" },
  "SM" => { "full_name" => "San Marino" },
  "GU" => { "full_name" => "Guam" },
  "MG" => { "full_name" => "Madagascar" },
  "TD" => { "full_name" => "Chad" },
  "VI" => { "full_name" => "U.S. Virgin Islands" },
  "GM" => { "full_name" => "Gambia" },
  "WS" => { "full_name" => "Samoa" },
  "BS" => { "full_name" => "Bahamas" },
  "TM" => { "full_name" => "Turkmenistan" },
  "TL" => { "full_name" => "Timor-Leste" },
  "NE" => { "full_name" => "Niger" },
  "TG" => { "full_name" => "Togo" },
  "SY" => { "full_name" => "Syria" },
  "CU" => { "full_name" => "Cuba" },
  "GQ" => { "full_name" => "Equatorial Guinea" },
  "JE" => { "full_name" => "Jersey" },
  "FO" => { "full_name" => "Faroe Islands" },
  "AG" => { "full_name" => "Antigua and Barbuda" },
  "GD" => { "full_name" => "Grenada" },
  "SB" => { "full_name" => "Solomon Islands" },
  "MF" => { "full_name" => "Saint Martin" },
  "GF" => { "full_name" => "French Guiana" },
  "BL" => { "full_name" => "Saint Barthélemy" },
  "LC" => { "full_name" => "Saint Lucia" },
  "YE" => { "full_name" => "Yemen" },
  "PF" => { "full_name" => "French Polynesia" },
  "GY" => { "full_name" => "Guyana" },
  "SR" => { "full_name" => "Suriname" },
  "BQ" => { "full_name" => "British Antarctic Territory" },
  "RE" => { "full_name" => "Réunion" },
  "TO" => { "full_name" => "Tonga" },
  "FM" => { "full_name" => "Micronesia" },
  "MR" => { "full_name" => "Mauritania" },
  "GP" => { "full_name" => "Guadeloupe" },
  "DM" => { "full_name" => "Dominica" },
  "KI" => { "full_name" => "Kiribati" },
  "KN" => { "full_name" => "Saint Kitts and Nevis" },
  "NU" => { "full_name" => "Niue" },
  "TK" => { "full_name" => "Tokelau" },
  "CF" => { "full_name" => "Central African Republic" },
  "AW" => { "full_name" => "Aruba" },
  "AI" => { "full_name" => "Anguilla" },
  "GG" => { "full_name" => "Guernsey" },
  "NR" => { "full_name" => "Nauru" },
  "CV" => { "full_name" => "Cape Verde" },
  "AS" => { "full_name" => "American Samoa" },
  "DJ" => { "full_name" => "Djibouti" },
  "VA" => { "full_name" => "Vatican City" },
  "PW" => { "full_name" => "Palau" },
  "ET" => { "full_name" => "Ethiopia" },
  "ST" => { "full_name" => "São Tomé and Príncipe" },
  "GW" => { "full_name" => "Guinea-Bissau" },
  "MC" => { "full_name" => "Monaco" },
  "TV" => { "full_name" => "Tuvalu" },
  "TC" => { "full_name" => "Turks and Caicos Islands" },
  "GL" => { "full_name" => "Greenland" },
  "AX" => { "full_name" => "Åland Islands" },
  "KM" => { "full_name" => "Comoros" },
  "YT" => { "full_name" => "Mayotte" },
  "NF" => { "full_name" => "Norfolk Island" },
  "UM" => { "full_name" => "U.S. Minor Outlying Islands" },
  "ER" => { "full_name" => "Eritrea" },
  "KP" => { "full_name" => "North Korea" },
  "IO" => { "full_name" => "British Indian Ocean Territory" },
  "MP" => { "full_name" => "Northern Mariana Islands" },
  "MQ" => { "full_name" => "Martinique" },
  "FK" => { "full_name" => "Falkland Islands" },
  "PM" => { "full_name" => "Saint Pierre and Miquelon" },
  "MH" => { "full_name" => "Marshall Islands" },
  "CK" => { "full_name" => "Cook Islands" },
  "AD" => { "full_name" => "Andorra" },
  "WF" => { "full_name" => "Wallis and Futuna" },
  "VC" => { "full_name" => "Saint Vincent and the Grenadines" }
}.freeze
